### ISSUE TITLE
Friendly JSON alternative

### ISSUE THREAD

**Issue by antaranyan** [gnuni/play#2]
Pick one of

- Hjson
- JSON5
- YAML
- TOML

Selected format must provide tooling for conversion to standard formats (i.e. JSON)

https://app.leanboard.io/board/82a877ba-4a74-4fce-8ca3-4f3cfa72ed3a

**Comment by antaranyan** [comment]
## TOML [:octocat:](https://github.com/toml-lang/toml)

> Tom's Obvious, Minimal Language.

### Example

```toml
# This is a TOML document.

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00 # First class dates

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true

[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]

# Line breaks are OK when inside arrays
hosts = [
  "alpha",
  "omega"
]
```

### Footnotes

- Node.js libs w/ spec. support - https://shared.by.re-becca.org/misc/TOML-SPEC-SUPPORT.html
